---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-admin-sa
  namespace: cattle-fleet-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-admin-role
rules:
  - apiGroups: ["fleet.cattle.io"]
    resources:
      - bundledeployments
      - bundlenamespacemappings
      - bundles
      - clustergroups
      - clusterregistrations
      - clusterregistrationtokens
      - clusters
      - contents
      - fleetworkspaces
      - gitreporestrictions
      - gitrepos
      - helmapps
      - imagescans
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fleet-admin-role
subjects:
  - kind: ServiceAccount
    name: fleet-admin-sa
    namespace: cattle-fleet-system

