---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-ci-sa
  namespace: cattle-fleet-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-ci-role
rules:
  - apiGroups: ["fleet.cattle.io"]
    resources:
      - clustergroups
      - clusters
      - gitreporestrictions
      - gitrepos
    verbs: ["get", "list", "watch","update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fleet-ci-role
subjects:
  - kind: ServiceAccount
    name: fleet-ci-sa
    namespace: cattle-fleet-system

