apiVersion: batch/v1
kind: Job
metadata:
  name: prepull-job
spec:
  template:
    spec:
      containers:
      - name: pre-pull
        image: nginx:1.27.5-perl
        command: ["sleep", "1"]
      restartPolicy: Never
