apiVersion: batch/v1
kind: Job
metadata:
  name: prepull-job
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: pre-pull
        image: nginx:stable-bookworm-perl
        command: ["sleep", "1"]
      restartPolicy: Never
